name: "Image Roulette"
description: "Servers a random image from a local folder on the network"
version: "0.1.0"
slug: "image"
init: false
map:
  - media
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5000/tcp: 6543
webui: http://[HOST]:[PORT:5000]/random
options:
  images_directory: "/media"
  period_seconds: "600"
schema:
  images_directory: str
  period_seconds: int(0,)
